---
# Configuring system for Placement Drives
- hosts: all
  become: yes
  become_method: sudo
  
  tasks:
  - name: Installing 9 items - jre,gcc,python3,net-tools,dia,texmaker,kile,chrome,chromium
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - default-jre
      - gcc-4.8
      - python3
      - net-tools
      - dia
      - texmaker
      - kile
      - chromium-browser
