---
# Installing All Essential tools for LAB 301
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: Installing all essential LAB 301
    apt:
      name: "{{ item }}"
    with_items:
      - umbrello
      - gcc
      - planner
      - texmaker
      - hping3
      - kile
      - wireshark
