---
# Installing All Essential tools for networking for lab 313 ( Faster Process )
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: Installing all essential Networking tools
    apt:
      name: "{{ item }}"
    with_items:
      - nmap
      - iftop
      - vnstat
      - iptraf
      - hping3
      - dstat
      - bmon
      - tcpdump
      - wireshark