---
# Installing All Essential tools for LAB 405
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: Installing all essential tools for LAB 405
    apt:
      name: "{{ item }}"
    with_items:
      - weka
      - python3
      - r-base	
